Removed what looked to be a typo, was causing SyntaxError
Traceback (most recent call last):
  File "EV3-Firmware_Check.py", line 15, in <module>
    from BrickPi import *   #import BrickPi.py file to use BrickPi operations
  File "/home/pi/Desktop/BrickPi_Python/Sensor_Examples/EV3BETA/BrickPi.py", line 138
    =======
     ^
SyntaxError: invalid syntax